version: "3"
services:
    db: 
        image: postgres:12
        container_name: queues-db
        environment:
            POSTGRES_USER: queues
            POSTGRES_DB: queues
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
    
    server:
        build: 
            context: ./http
        container_name: queues-server
        ports:
            - "8888:8888"
        depends_on: 
            - db
        volumes:
            - ./http/server:/opt/server
    
#    queue-publish:
    
#    queue-subscribe:
    
#    g:
#        image: guillotina/guillotina:latest
#        container_name: guillotina
#        depends_on: 
#            - db
#        ports:
#            - "127.0.0.1:8080:8080"
#        command:
#            - g
#            - -c
#            - '{"databases": [{"db": {"storage": "postgresql", "dsn": "postgres://guillotina:@db/guillotina"}}], "root_user": {"password": "root"}}'

