version: "3"
services:
    db: 
        image: postgres:12
        container_name: queues-db
        environment:
            POSTGRES_USER: queues
            POSTGRES_DB: queues
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
    
    server:
        build: 
            context: ./http
        container_name: queues-server
        ports:
            - "8888:8888"
        depends_on: 
            - db
        volumes:
            - ./out:/opt/queues
        command: ["python3", "/opt/queue/queue_server.py"]
    
